import { Tool } from "../types";

export const PERMANENT_TOOLS: Tool[] = [
  {
    id: "perm-chatgpt",
    name: "ChatGPT",
    tagline: "The world's most popular AI assistant by OpenAI.",
    description: "ChatGPT is a sibling model to InstructGPT, which is trained to follow an instruction in a prompt and provide a detailed response.",
    url: "https://chat.openai.com",
    website: "https://chat.openai.com",
    votesCount: 9999,
    createdAt: new Date().toISOString(),
    thumbnail: { url: "https://picsum.photos/seed/chatgpt/200/200" },
    topics: { edges: [{ node: { name: "AI Assistant" } }, { node: { name: "Productivity" } }] }
  },
  {
    id: "perm-claude",
    name: "Claude",
    tagline: "Next-generation AI assistant by Anthropic.",
    description: "Claude is a next-generation AI assistant based on Anthropic’s research into training helpful, honest, and harmless AI systems.",
    url: "https://claude.ai",
    website: "https://claude.ai",
    votesCount: 9998,
    createdAt: new Date().toISOString(),
    thumbnail: { url: "https://picsum.photos/seed/claude/200/200" },
    topics: { edges: [{ node: { name: "AI Assistant" } }, { node: { name: "Writing" } }] }
  },
  {
    id: "perm-perplexity",
    name: "Perplexity",
    tagline: "AI-powered search engine for instant answers.",
    description: "Perplexity AI is an AI-powered search engine and chatbot that uses large language models to provide accurate and informative answers to user queries.",
    url: "https://www.perplexity.ai",
    website: "https://www.perplexity.ai",
    votesCount: 9997,
    createdAt: new Date().toISOString(),
    thumbnail: { url: "https://picsum.photos/seed/perplexity/200/200" },
    topics: { edges: [{ node: { name: "AI Search" } }, { node: { name: "Productivity" } }] }
  },
  {
    id: "perm-gemini",
    name: "Gemini",
    tagline: "Google's most capable AI model.",
    description: "Gemini is Google's largest and most capable AI model, built to be multimodal and optimized for different sizes.",
    url: "https://gemini.google.com",
    website: "https://gemini.google.com",
    votesCount: 9996,
    createdAt: new Date().toISOString(),
    thumbnail: { url: "https://picsum.photos/seed/gemini/200/200" },
    topics: { edges: [{ node: { name: "AI Assistant" } }, { node: { name: "Productivity" } }] }
  },
  {
    id: "perm-copilot",
    name: "Microsoft Copilot",
    tagline: "Your everyday AI companion by Microsoft.",
    description: "Microsoft Copilot is an AI-powered companion that works across your favorite apps to help you be more productive.",
    url: "https://copilot.microsoft.com",
    website: "https://copilot.microsoft.com",
    votesCount: 9995,
    createdAt: new Date().toISOString(),
    thumbnail: { url: "https://picsum.photos/seed/copilot/200/200" },
    topics: { edges: [{ node: { name: "AI Assistant" } }, { node: { name: "Productivity" } }] }
  },
  {
    id: "perm-notion-ai",
    name: "Notion AI",
    tagline: "AI integrated directly into your Notion workspace.",
    description: "Notion AI is a suite of AI-powered features integrated directly into the Notion workspace to help you write, plan, and create.",
    url: "https://www.notion.so/product/ai",
    website: "https://www.notion.so/product/ai",
    votesCount: 9994,
    createdAt: new Date().toISOString(),
    thumbnail: { url: "https://picsum.photos/seed/notion/200/200" },
    topics: { edges: [{ node: { name: "Productivity" } }] }
  },
  {
    id: "perm-grammarly",
    name: "Grammarly AI",
    tagline: "AI-powered writing assistant for better communication.",
    description: "Grammarly's AI writing assistant helps you write clearly and confidently across all your favorite apps.",
    url: "https://www.grammarly.com",
    website: "https://www.grammarly.com",
    votesCount: 9993,
    createdAt: new Date().toISOString(),
    thumbnail: { url: "https://picsum.photos/seed/grammarly/200/200" },
    topics: { edges: [{ node: { name: "Writing" } }] }
  },
  {
    id: "perm-jasper",
    name: "Jasper AI",
    tagline: "AI content platform for enterprise teams.",
    description: "Jasper is the AI content platform that helps enterprise teams create high-quality content faster.",
    url: "https://www.jasper.ai",
    website: "https://www.jasper.ai",
    votesCount: 9992,
    createdAt: new Date().toISOString(),
    thumbnail: { url: "https://picsum.photos/seed/jasper/200/200" },
    topics: { edges: [{ node: { name: "Writing" } }, { node: { name: "Marketing" } }] }
  },
  {
    id: "perm-midjourney",
    name: "Midjourney",
    tagline: "Generative AI for stunning visual art.",
    description: "Midjourney is an independent research lab exploring new mediums of thought and expanding the imaginative powers of the human species.",
    url: "https://www.midjourney.com",
    website: "https://www.midjourney.com",
    votesCount: 9991,
    createdAt: new Date().toISOString(),
    thumbnail: { url: "https://picsum.photos/seed/midjourney/200/200" },
    topics: { edges: [{ node: { name: "Image" } }, { node: { name: "Design" } }] }
  },
  {
    id: "perm-leonardo",
    name: "Leonardo AI",
    tagline: "Generative AI platform for creators.",
    description: "Leonardo AI is a generative AI platform that allows creators to generate high-quality assets for their projects.",
    url: "https://leonardo.ai",
    website: "https://leonardo.ai",
    votesCount: 9990,
    createdAt: new Date().toISOString(),
    thumbnail: { url: "https://picsum.photos/seed/leonardo/200/200" },
    topics: { edges: [{ node: { name: "Image" } }, { node: { name: "Design" } }] }
  },
  {
    id: "perm-firefly",
    name: "Adobe Firefly",
    tagline: "Adobe's family of creative generative AI models.",
    description: "Adobe Firefly is a family of creative generative AI models that are integrated into Adobe's Creative Cloud apps.",
    url: "https://firefly.adobe.com",
    website: "https://firefly.adobe.com",
    votesCount: 9989,
    createdAt: new Date().toISOString(),
    thumbnail: { url: "https://picsum.photos/seed/firefly/200/200" },
    topics: { edges: [{ node: { name: "Image" } }, { node: { name: "Design" } }] }
  },
  {
    id: "perm-runway",
    name: "Runway",
    tagline: "AI-powered video generation and editing tools.",
    description: "Runway is an applied AI research company shaping the next era of art, entertainment and human creativity.",
    url: "https://runwayml.com",
    website: "https://runwayml.com",
    votesCount: 9988,
    createdAt: new Date().toISOString(),
    thumbnail: { url: "https://picsum.photos/seed/runway/200/200" },
    topics: { edges: [{ node: { name: "Video" } }, { node: { name: "Design" } }] }
  },
  {
    id: "perm-pika",
    name: "Pika Labs",
    tagline: "An idea-to-video platform that brings your imagination to life.",
    description: "Pika is an idea-to-video platform that allows anyone to bring their imagination to life through video.",
    url: "https://pika.art",
    website: "https://pika.art",
    votesCount: 9987,
    createdAt: new Date().toISOString(),
    thumbnail: { url: "https://picsum.photos/seed/pika/200/200" },
    topics: { edges: [{ node: { name: "Video" } }, { node: { name: "Design" } }] }
  },
  {
    id: "perm-github-copilot",
    name: "GitHub Copilot",
    tagline: "Your AI pair programmer by GitHub.",
    description: "GitHub Copilot uses the OpenAI Codex to suggest code and entire functions in real-time, right from your editor.",
    url: "https://github.com/features/copilot",
    website: "https://github.com/features/copilot",
    votesCount: 9986,
    createdAt: new Date().toISOString(),
    thumbnail: { url: "https://picsum.photos/seed/github/200/200" },
    topics: { edges: [{ node: { name: "Coding" } }] }
  },
  {
    id: "perm-cursor",
    name: "Cursor",
    tagline: "The AI-first code editor.",
    description: "Cursor is an AI-powered code editor that helps you write, edit, and chat with your code.",
    url: "https://cursor.sh",
    website: "https://cursor.sh",
    votesCount: 9985,
    createdAt: new Date().toISOString(),
    thumbnail: { url: "https://picsum.photos/seed/cursor/200/200" },
    topics: { edges: [{ node: { name: "Coding" } }] }
  },
  {
    id: "perm-codeium",
    name: "Codeium",
    tagline: "Free AI code acceleration for individuals.",
    description: "Codeium is a free AI-powered code acceleration tool that provides autocomplete, search, and chat for developers.",
    url: "https://codeium.com",
    website: "https://codeium.com",
    votesCount: 9984,
    createdAt: new Date().toISOString(),
    thumbnail: { url: "https://picsum.photos/seed/codeium/200/200" },
    topics: { edges: [{ node: { name: "Coding" } }] }
  },
  {
    id: "perm-elevenlabs",
    name: "ElevenLabs",
    tagline: "The most realistic AI speech software.",
    description: "ElevenLabs is an American software company that develops natural-sounding speech synthesis and text-to-speech software.",
    url: "https://elevenlabs.io",
    website: "https://elevenlabs.io",
    votesCount: 9983,
    createdAt: new Date().toISOString(),
    thumbnail: { url: "https://picsum.photos/seed/elevenlabs/200/200" },
    topics: { edges: [{ node: { name: "Voice" } }, { node: { name: "Automation" } }] }
  }
];
